# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mblog', '0004_auto_20160912_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='UserPost',
        ),
    ]
