# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mblog', '0007_auto_20160912_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='post date',
        ),
    ]
