# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mblog', '0009_auto_20160913_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='post text',
            new_name='post_text',
        ),
        migrations.RenameField(
            model_name='userpost',
            old_name='post user',
            new_name='post_user',
        ),
    ]
