# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mblog', '0010_auto_20160913_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
