# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mblog', '0011_userpost_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post_date',
            field=models.DateTimeField(),
        ),
    ]
